[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
redstone_sol = "redumH9C5NCb4bMUcf5SjE3ANkLSLMTx8L1WPmuHbAR"

[programs.devnet]
redstone_sol = "redumH9C5NCb4bMUcf5SjE3ANkLSLMTx8L1WPmuHbAR"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "npm run test"
